# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MmeshNode < Formula
  desc "mmesh-node agent"
  homepage "https://mmesh.io"
  version "0.9.4"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mmesh/m-node/releases/download/v0.9.4/mmesh-node_0.9.4_darwin_arm64.tar.gz"
      sha256 "2eb080ab377db73047c29fb4a7eee20f3556d24f11fce499f4d3f04d57f3e141"

      def install
        bin.install "mmesh-node"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mmesh/m-node/releases/download/v0.9.4/mmesh-node_0.9.4_darwin_amd64.tar.gz"
      sha256 "666f9a5fd7f9d87b921182824c8d314531e274b4e8882b86997a780d4bac32c8"

      def install
        bin.install "mmesh-node"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmesh/m-node/releases/download/v0.9.4/mmesh-node_0.9.4_linux_arm64.tar.gz"
      sha256 "2575ea8cec20ce3a5466a273429464a13f5c51cacc198c16920d8671923c4f9c"

      def install
        bin.install "mmesh-node"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mmesh/m-node/releases/download/v0.9.4/mmesh-node_0.9.4_linux_amd64.tar.gz"
      sha256 "db3f2d0a369f1571360272ce6e28a17d370c8cfe4ac65e80eea704d47b700ae6"

      def install
        bin.install "mmesh-node"
      end
    end
  end
end
